services:
  web:
    build: ./frontend
    container_name: edsistant-web
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_PUBLIC_KEY}
  backend:
    build: ./backend
    container_name: edsistant-api
    restart: always
    environment:
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
  nginx:
    image: nginx:1.27.0-alpine
    labels: 
      - sh.acme.autoload.domain=edsistant.com
    container_name: edsistant-nginx 
    restart: always
    environment:
      - SITE_URL=${SITE_URL}
    links: 
      - backend
      - web
    depends_on: 
      - web
      - backend
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template
      - web-root:/var/www/edsistant
volumes:
  web-root:
    external: true
