services:
  web:
    build: ./frontend
    container_name: edsistant-web
    restart: always
    ports: 
      - 3000:3000
  backend:
    build: ./backend
    container_name: edsistant-api
    restart: always
    ports:
      - 8090:8080
    environment:
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
  nginx:
    image: nginx:1.27.0-alpine
    labels: 
      - sh.acme.autoload.domain=edsistant.com
    container_name: edsistant-nginx 
    restart: always
    environment:
      - SITE_URL=${SITE_URL}
    ports: 
      - 809:80
      - 4430:443
    links: 
      - backend
      - web
    depends_on: 
      - web
      - backend
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template
      - web-root:/var/www/edsistant
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh    
    command: daemon
    volumes:
      - ./acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=edsistant.com
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/live/edsistant.com/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/live/edsistant.com/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/live/edsistant.com/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/live/edsistant.com/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"
volumes:
  web-root:
    external: true
