services:
  web:
    build: ./frontend
    container_name: edsistant-web
    restart: always
    ports: 
      - 3000:3000
  backend:
    build: ./backend
    container_name: edsistant-api
    restart: always
    ports:
      - 8090:8080
    environment:
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    environment:
      - URL=${SITE_URL}
  nginx:
    image: nginx:1.27.0-alpine
    container_name: edsistant-nginx 
    restart: always
    environment:
      - URL=${SITE_URL}
    ports: 
      - 80:80
      - 443:443
    links: 
      - backend
      - web
    depends_on: 
      - web
      - backend
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/edsistant
      - ./certbot/www/:/var/www/certbot/:ro
volumes:
  web-root:
