services:
  web:
    build: ./frontend
    container_name: edsistant-web
    restart: always
    ports: 
      - 3000:3000
  backend:
    build: ./backend
    container_name: edsistant-api
    restart: always
    ports:
      - 8080:8080
    secrets:
      - db-password
      - supabase-service-key
  nginx:
    image: nginx:1.27.0-alpine
    container_name: edsistant-nginx 
    restart: always
    ports: 
      - 80:80
      - 443:443
    links: 
      - backend
      - web
    depends_on: 
      - web
      - backend
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/edsistant
volumes:
  web-root:
  pgdata:
secrets:
  db-password:
    environment: "POSTGRES_PASSWORD"
  supabase-service-key:
    environment: "SUPABASE_KEY"
